### ISSUE TITLE
RpcTimeoutError commit-configuration

### ISSUE THREAD

**Issue by csk06** [Juniper/ansible-junos-stdlib#582]
Issue Type
------

 - Bug Report

Module Name
------

juniper.device collection and Python libraries version

```
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True

junos-eznc==2.6.3
```

OS / Environment
------

Summary
------

Hi, I am trying to configure a lab device with following commands, but even for simple hostname changing, half of the times im getting the error below. As i understand, that "commit-configuration" is coming from python library, and there is variable to change that value something different from 10, but on ansible i guess there is no variable to change it. 

Steps to reproduce
------

```
- name: "Configure Device" 
  hosts: junos
  connection: local
  timeout: 50 
  gather_facts: no

  tasks:
    - name: "Configure op script"
      juniper.device.config:
        config_mode: "private"
        check_commit_wait: 20
        load: "set"
        src: "test.txt" 
      register: response
    - name: "Print the config changes"
      debug:
        var: response
```

Expected results

```

```
Actual results
------

```
fatal: [172.31.30.158]: FAILED! => {"changed": false, "msg": "Failure checking the configuraton: RpcTimeoutError(host: 172.31.30.158, cmd: commit-configuration, timeout: 10)"}
```

**Comment by ric79** [comment]
Same error for me

Failure committing the configuraton: RpcTimeoutError(host: xx.xx.xx.xx, cmd: commit-configuration, timeout: 10)

Did you solve it?

```
    - juniper.device.config:
        load: "merge"
        lines:
           - ....
        comment: "..."
        commit: true
        commit_empty_changes: true
        config_mode: "exclusive"
      vars:
        ansible_connection: local

```

**Comment by ric79** [comment]
Workaround:

https://github.com/Juniper/ansible-junos-stdlib/blob/master/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py#L1529

```
        self.logger.debug("Committing the configuration.")
        try:
            self.config.commit(ignore_warning=ignore_warning,
                               comment=comment,
                               confirm=confirmed,
                               timeout=900, <-------------------- ADDED
                               full=full)
            self.logger.debug("Configuration committed.")
        except (self.pyez_exception.RpcError,
                self.pyez_exception.ConnectError) as ex:
            self.fail_json(msg='Failure committing the configuraton: %s' %
                               (str(ex)))
```

**Comment by dineshbaburam91** [comment]
Fixed the issue  #588

**Comment by TheMysteriousX** [comment]
#588 doesn't fix the issue for me - instead of a 10 second timeout, it makes a 30 second timeout be applied instead.

The change appears to add timeout support to commit_configuration, but the invocation of the method hasn't been updated - so instead of the timeout defined in the task being applied, the default of 30s is used.

https://github.com/Juniper/ansible-junos-stdlib/blob/master/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py#L1174-L1177

```fatal: [...]: FAILED! => {"changed": false, "msg": "Failure committing the configuraton: RpcTimeoutError(host: ..., cmd: commit-configuration, timeout: 30)"}```

```
- name: Commit Confirm
  juniper.device.config:
    user: "{{ junos_user }}"
    load: 'override'
    timeout: 180 # <<<<< timeout not respected
    confirm: 10
    check_commit_wait: 3
    src: "{{ build_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.conf"
    ignore_warning:
      - Delete all fabric member interfaces
    comment: "{{ comment }}"
  register: commit_reponse
  when: confirm
```

**Comment by sibiantony** [comment]
Have the same issue. Changing the default in `commit_configuration` works.

Shouldn't the `timeout` be forwarded here? https://github.com/Juniper/ansible-junos-stdlib/blob/master/ansible_collections/juniper/device/plugins/modules/config.py#L1197

**Comment by GiuffreLab** [comment]
Still seeing this issue 5/13/2024.

Has anyone figured out a fix on the Ansible side for the RPC timeout not respecting the timeout variable?
